title: LLM Projects & Resources
logo: /assets/img/logo.png
description: Keeping track of LLM projects and resources as they come about and make progress
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
